name: netwrk
description: A LinkedIn meets TikTok social network app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  timeago: ^3.6.0
  path: ^1.8.3
  video_player: ^2.8.2
  camera: ^0.10.5+9
  video_compress: ^3.1.2
  path_provider: ^2.1.2
  video_thumbnail: ^0.5.3
  device_info_plus: ^9.1.2
  collection: ^1.17.2
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  latlong2: ^0.9.0
  google_places_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/videos/ 