import 'dart:io';
import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart' hide Provider;
import 'package:supabase_flutter/supabase_flutter.dart';
import '../core/supabase_config.dart';

final supabaseProvider = StateProvider<SupabaseClient>((ref) {
  return Supabase.instance.client;
});

final authProvider = StateNotifierProvider<AuthNotifier, User?>((ref) {
  return AuthNotifier(ref.watch(supabaseProvider));
});

class AuthNotifier extends StateNotifier<User?> {
  final SupabaseClient _supabase;

  AuthNotifier(this._supabase) : super(_supabase.auth.currentUser) {
    _supabase.auth.onAuthStateChange.listen((data) {
      state = data.session?.user;
    });
  }

  Future<void> signUp({
    required String email,
    required String password,
  }) async {
    try {
      final AuthResponse res = await _supabase.auth.signUp(
        email: email,
        password: password,
      );

      if (res.user == null) {
        throw Exception('Sign up failed - no user returned');
      }

      // Create initial profile - username will be auto-generated by database trigger
      await _supabase.from('profiles').insert({
        'id': res.user!.id,
        'email': email,
        'created_at': DateTime.now().toIso8601String(),
        'updated_at': DateTime.now().toIso8601String(),
      });

    } catch (error) {
      print('Sign up error: $error');
      if (error is PostgrestException) {
        throw Exception('Database error: ${error.message}');
      } else if (error is AuthException) {
        throw Exception('Auth error: ${error.message}');
      } else {
        throw Exception('Unexpected error during sign up: $error');
      }
    }
  }

  Future<void> signIn({
    required String email,
    required String password,
  }) async {
    try {
      final response = await _supabase.auth.signInWithPassword(
        email: email,
        password: password,
      );

      if (response.user == null) {
        throw Exception('Sign in failed - no user returned');
      }

      // Check if email is confirmed
      if (response.user!.emailConfirmedAt == null) {
        throw Exception('Please confirm your email before signing in');
      }

      // Check if profile exists, create if it doesn't
      try {
        await _supabase
            .from('profiles')
            .select()
            .eq('id', response.user!.id)
            .single();
      } catch (e) {
        await _supabase.from('profiles').insert({
          'id': response.user!.id,
          'email': response.user!.email,
          'created_at': DateTime.now().toIso8601String(),
          'updated_at': DateTime.now().toIso8601String(),
        });
      }

    } catch (error) {
      if (error is PostgrestException) {
        throw Exception('Database error: ${error.message}');
      } else if (error is AuthException) {
        throw Exception('Auth error: ${error.message}');
      } else {
        throw Exception(error.toString());
      }
    }
  }

  Future<void> signOut() async {
    await _supabase.auth.signOut();
  }

  Future<void> updateProfile({
    String? username,
    String? fullName,
    String? avatarUrl,
    String? bio,
    String? website,
  }) async {
    final user = state;
    if (user == null) throw Exception('Must be logged in to update profile');

    try {
      await _supabase
          .from('profiles')
          .update({
            if (username != null) 'username': username,
            if (fullName != null) 'full_name': fullName,
            if (avatarUrl != null) 'avatar_url': avatarUrl,
            if (bio != null) 'bio': bio,
            if (website != null) 'website': website,
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('id', user.id);
    } catch (error) {
      throw Exception('Failed to update profile: $error');
    }
  }
} 